schema_version: 1

context:
  name: bioio-ome-zarr
  version: 2.3.0
  python_min: 3.11

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/bioio_ome_zarr-${{ version }}.tar.gz
  sha256: ee048bcdfa4718d3d048d8ee1089e97e0feeb6a0773c09571104d7085c92c61c

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=65
    - wheel
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=${{ python_min }}
    - bioio-base >=1.4.0
    - fsspec >=2022.8.0
    - aiohttp >=3.12.15,<4.0.0
    - s3fs >=2023.9.0
    - scikit-image !=0.23.0
    - xarray >=0.16.1
    - zarr >=3.1.0,<3.1.2

tests:
  - python:
      imports:
        - bioio_ome_zarr
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: A BioIO reader plugin for reading Zarr files in the OME format.
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/bioio-devs/bioio-ome-zarr

extra:
  recipe-maintainers:
    - imagejan
